version: "3.8"

services:

  # AD-CNAS and WSUS-CNAS removed — replaced by real Windows VMs

  proxy-cnas:
    image: ubuntu/squid:latest
    container_name: PROXY-CNAS-KOLEA
    hostname: PROXY-CNAS-KOLEA
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - proxy-logs:/var/log/squid
    networks:
      - cnas-net

  websrv-cnas:
    image: nginx:latest
    container_name: WEBSRV-CNAS-KOLEA
    hostname: WEBSRV-CNAS-KOLEA
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - websrv-logs:/var/log/nginx
    networks:
      - cnas-net

volumes:
  proxy-logs:
    driver: local
  websrv-logs:
    driver: local

networks:
  cnas-net:
    external: true
    name: elk_stack_elastic-net
